# Generated by Django 6.1.1 on 2026-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='gardener_prompt',
            field=models.TextField(blank=True, default='', help_text='Custom gardener persona for AI generation. Empty = default expert.'),
        ),
    ]
