# Generated by Django 6.0.4 on 2026-04-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_expansion_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='events.calendarevent'),
        ),
    ]
